# Chosing, exploring and wrangling data set - Content list

1. Introduction
2. Import libraries and data
3. Explore and clean TGV data set
4. Explore and clean Number of travelers data set

# 1. Introduction

For this project, I decided to work with open data from SNCF, France's national state-owned railway company. All the data I will use in this project is open and was found on their website https://ressources.data.sncf.com/. I will combine several data sets in order to find relationships between different variables, such as the delays experienced in the train station, the number of passengers per year in a given train station, the region from which the train left, amongst others.

# 2. Import libraries and data

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Create path
path = r'C:\Users\Mathilde\Documents\DATA ANALYSIS CAREERFOUNDRY\Aug 2024 - SNCF project'
# Data set on the delays on the TGV (high speed trains)
df_delay_tgv = pd.read_csv(os.path.join(path, '02 Data', 'Original data', 'regularite-mensuelle-tgv-aqst.csv'), index_col = False, delimiter=';')
#  Data set on the number of passengers in the train stations
df_nb_travelers = pd.read_csv(os.path.join(path, '02 Data', 'Original data', 'frequentation-gares.csv'), index_col = False, delimiter=';')

# 3. Explore and clean TGV data set

In [3]:
pd.set_option('display.max_columns', None)
df_delay_tgv.head()

,Date,Service,Gare de départ,Gare d'arrivée,Durée moyenne du trajet,Nombre de circulations prévues,Nombre de trains annulés,Commentaire annulations,Nombre de trains en retard au départ,Retard moyen des trains en retard au départ,Retard moyen de tous les trains au départ,Commentaire retards au départ,Nombre de trains en retard à l'arrivée,Retard moyen des trains en retard à l'arrivée,Retard moyen de tous les trains à l'arrivée,Commentaire retards à l'arrivée,Nombre trains en retard > 15min,Retard moyen trains en retard > 15 (si liaison concurrencée par vol),Nombre trains en retard > 30min,Nombre trains en retard > 60min,Prct retard pour causes externes,Prct retard pour cause infrastructure,Prct retard pour cause gestion trafic,Prct retard pour cause matériel roulant,Prct retard pour cause gestion en gare et réutilisation de matériel,"Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)"
0,2018-01,National,BORDEAUX ST JEAN,PARIS MONTPARNASSE,141,870,5,NaN,289,11.247809,3.693179,NaN,147,28.436735,6.511118,NaN,110,6.511118,44,8,36.134454,31.092437,10.924370,15.966387,5.042017,0.840336
1,2018-01,National,LA ROCHELLE VILLE,PARIS MONTPARNASSE,165,222,0,NaN,8,2.875000,0.095796,NaN,34,21.524020,5.696096,NaN,22,5.696096,5,0,15.384615,30.769231,38.461538,11.538462,3.846154,0.000000
2,2018-01,National,PARIS MONTPARNASSE,QUIMPER,220,248,1,NaN,37,9.501351,1.003981,NaN,26,55.692308,7.578947,"Ce mois-ci, l'OD a été touchée par les inciden...",26,7.548387,17,7,26.923077,38.461538,15.384615,19.230769,0.000000,0.000000
3,2018-01,National,PARIS MONTPARNASSE,ST MALO,156,102,0,NaN,12,19.912500,1.966667,NaN,13,48.623077,6.790686,"Ce mois-ci, l'OD a été touchée par les inciden...",8,6.724757,6,4,23.076923,46.153846,7.692308,15.384615,7.692308,0.000000
4,2018-01,National,PARIS MONTPARNASSE,ST PIERRE DES CORPS,61,391,2,NaN,61,7.796995,0.886889,NaN,71,12.405164,3.346487,NaN,17,3.346487,6,0,21.212121,42.424242,9.090909,21.212121,6.060606,0.000000

In [4]:
df_delay_tgv.shape

(9598, 26)

In [5]:
df_delay_tgv.describe()

,Durée moyenne du trajet,Nombre de circulations prévues,Nombre de trains annulés,Commentaire annulations,Nombre de trains en retard au départ,Retard moyen des trains en retard au départ,Retard moyen de tous les trains au départ,Commentaire retards au départ,Nombre de trains en retard à l'arrivée,Retard moyen des trains en retard à l'arrivée,Retard moyen de tous les trains à l'arrivée,Nombre trains en retard > 15min,Retard moyen trains en retard > 15 (si liaison concurrencée par vol),Nombre trains en retard > 30min,Nombre trains en retard > 60min,Prct retard pour causes externes,Prct retard pour cause infrastructure,Prct retard pour cause gestion trafic,Prct retard pour cause matériel roulant,Prct retard pour cause gestion en gare et réutilisation de matériel,"Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)"
count,9598.000000,9598.000000,9598.000000,0.0,9598.000000,9598.000000,9598.000000,0.0,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000
mean,170.010940,265.281413,10.070744,NaN,87.775891,11.597082,3.056784,NaN,36.074495,34.170000,5.785380,25.588248,33.754032,12.169098,4.459158,22.074921,21.992758,19.730230,19.048353,7.072200,7.445573
std,87.300663,178.879185,24.784164,NaN,89.711554,11.918225,5.097969,NaN,30.557789,15.491757,7.469440,21.927697,19.720504,11.440176,5.079933,16.423143,15.346118,14.965066,13.903218,8.094415,9.960441
min,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,-229.269444,NaN,0.000000,-40.109259,-472.638889,0.000000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,100.000000,147.000000,0.000000,NaN,22.000000,5.588875,1.165647,NaN,14.000000,24.967716,3.245905,10.000000,22.725868,4.000000,1.000000,10.714286,11.764706,9.523810,10.000000,0.000000,0.000000
50%,163.000000,227.000000,2.000000,NaN,54.000000,9.565817,2.260175,NaN,28.000000,32.599802,5.103441,20.000000,35.971216,9.000000,3.000000,20.000000,20.000000,17.857143,17.274536,5.555556,4.477612
75%,222.000000,346.000000,8.000000,NaN,128.000000,14.724359,3.897177,NaN,49.000000,41.365968,7.783922,35.000000,44.931399,17.000000,6.000000,30.769231,30.000000,27.586207,26.000000,10.569227,11.111111
max,786.000000,1100.000000,297.000000,NaN,596.000000,316.188095,84.516667,NaN,376.000000,299.600000,92.000000,312.000000,299.600000,202.000000,71.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

The columns "Commentaire annulations" and "Commentaire retards au départ" are empty (and if they had containedanything, it would have been unstructured data -  comments about the cancellations and delays). Let's remove them.

I will also rename all the columns to translate them to English before going further.

##  3.1 Drop the empty columns

In [6]:
df_delay_tgv = df_delay_tgv.drop(columns=['Commentaire annulations', 'Commentaire retards au départ'])

## 3.2 Rename columns to English

In [7]:
df_delay_tgv.rename(columns={
    "Gare de départ": "Departure station",
    "Gare d'arrivée": "Arrival station",
    "Durée moyenne du trajet": "Avg trip length",
    "Nombre de circulations prévues": "Number of trips scheduled",
    "Nombre de trains annulés": "Number of trains cancelled",
    "Nombre de trains en retard au départ": "Number of trains delayed on departure",
    "Retard moyen des trains en retard au départ": "Avg delay of trains delayed on departure",
    "Retard moyen de tous les trains au départ": "Avg delay of all trains on departure",
    "Nombre de trains en retard à l'arrivée": "Number of trains delayed on arrival",
    "Retard moyen des trains en retard à l'arrivée": "Avg delay of trains delayed on arrival",
    "Retard moyen de tous les trains à l'arrivée": "Avg delay of all trains on arrival",
    "Commentaire retards à l'arrivée" : "Comments delay on arrival",
    "Nombre trains en retard > 15min": "Number of trains >15 min delay",
    "Retard moyen trains en retard > 15 (si liaison concurrencée par vol)": "Avg delay of trains >15 (if trip has a flight concurrence)",
    "Nombre trains en retard > 30min": "Number of trains >30 min delay",
    "Nombre trains en retard > 60min": "Number of trains >60 min delay",
    "Prct retard pour causes externes": "% delay from external causes",
    "Prct retard pour cause infrastructure": "% delay infrastructure cause",
    "Prct retard pour cause gestion trafic": "% delay traffic management cause",
    "Prct retard pour cause matériel roulant": "% delay rolling stock cause",
    "Prct retard pour cause gestion en gare et réutilisation de matériel": "% delay station management and reutilization of stock",
    "Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)": "% delay because of accommodation of passengers (crowd, disability, connections)"
}, inplace = True)

In [8]:
# Explore again
df_delay_tgv.describe()

,Avg trip length,Number of trips scheduled,Number of trains cancelled,Number of trains delayed on departure,Avg delay of trains delayed on departure,Avg delay of all trains on departure,Number of trains delayed on arrival,Avg delay of trains delayed on arrival,Avg delay of all trains on arrival,Number of trains >15 min delay,Avg delay of trains >15 (if trip has a flight concurrence),Number of trains >30 min delay,Number of trains >60 min delay,% delay from external causes,% delay infrastructure cause,% delay traffic management cause,% delay rolling stock cause,% delay station management and reutilization of stock,"% delay because of accommodation of passengers (crowd, disability, connections)"
count,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000
mean,170.010940,265.281413,10.070744,87.775891,11.597082,3.056784,36.074495,34.170000,5.785380,25.588248,33.754032,12.169098,4.459158,22.074921,21.992758,19.730230,19.048353,7.072200,7.445573
std,87.300663,178.879185,24.784164,89.711554,11.918225,5.097969,30.557789,15.491757,7.469440,21.927697,19.720504,11.440176,5.079933,16.423143,15.346118,14.965066,13.903218,8.094415,9.960441
min,0.000000,0.000000,0.000000,0.000000,0.000000,-229.269444,0.000000,-40.109259,-472.638889,0.000000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,100.000000,147.000000,0.000000,22.000000,5.588875,1.165647,14.000000,24.967716,3.245905,10.000000,22.725868,4.000000,1.000000,10.714286,11.764706,9.523810,10.000000,0.000000,0.000000
50%,163.000000,227.000000,2.000000,54.000000,9.565817,2.260175,28.000000,32.599802,5.103441,20.000000,35.971216,9.000000,3.000000,20.000000,20.000000,17.857143,17.274536,5.555556,4.477612
75%,222.000000,346.000000,8.000000,128.000000,14.724359,3.897177,49.000000,41.365968,7.783922,35.000000,44.931399,17.000000,6.000000,30.769231,30.000000,27.586207,26.000000,10.569227,11.111111
max,786.000000,1100.000000,297.000000,596.000000,316.188095,84.516667,376.000000,299.600000,92.000000,312.000000,299.600000,202.000000,71.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

The "min" shows some negative values in several columns with delay values: it shouldn't be possible. Let's check it out.

## 3.3 Deal with outliers/impossible values

In [9]:
# Identify rows with negative values
df_delay_tgv.loc[df_delay_tgv['Avg delay of all trains on departure'] < 0]

,Date,Service,Departure station,Arrival station,Avg trip length,Number of trips scheduled,Number of trains cancelled,Number of trains delayed on departure,Avg delay of trains delayed on departure,Avg delay of all trains on departure,Number of trains delayed on arrival,Avg delay of trains delayed on arrival,Avg delay of all trains on arrival,Comments delay on arrival,Number of trains >15 min delay,Avg delay of trains >15 (if trip has a flight concurrence),Number of trains >30 min delay,Number of trains >60 min delay,% delay from external causes,% delay infrastructure cause,% delay traffic management cause,% delay rolling stock cause,% delay station management and reutilization of stock,"% delay because of accommodation of passengers (crowd, disability, connections)"
416,2018-04,National,SAINT ETIENNE CHATEAUCREUX,PARIS LYON,170,81,18,8,4.945833,-1.066667,5,26.280000,3.248677,NaN,4,3.248677,2,0,33.333333,33.333333,0.000000,0.000000,33.333333,0.000000
478,2018-04,National,ST MALO,PARIS MONTPARNASSE,159,81,24,11,3.584848,-2.158187,17,19.013725,7.208480,"Ce mois-ci, l'OD a été touchée par la grève (1...",9,7.208480,1,0,17.647059,64.705882,5.882353,11.764706,0.000000,0.000000
487,2018-04,National,MARSEILLE ST CHARLES,TOURCOING,301,25,7,0,0.000000,-0.370370,0,0.000000,2.500000,NaN,0,2.500000,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
617,2018-05,International,GENEVE,PARIS LYON,180,217,59,8,14.875000,-1.759494,43,41.544186,11.452426,NaN,40,11.452426,29,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
654,2018-06,National,PARIS MONTPARNASSE,ST PIERRE DES CORPS,61,392,69,19,22.894737,-0.069247,64,15.905208,3.992931,NaN,14,3.992931,9,3,20.930233,27.906977,20.930233,16.279070,11.627907,2.325581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8098,2023-06,National,TOURCOING,BORDEAUX ST JEAN,305,30,0,0,0.000000,-0.004598,2,0.000000,1.117816,NaN,2,100.025000,2,2,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000
8492,2023-09,International,PARIS LYON,ITALIE,423,30,16,0,0.000000,-0.029762,0,0.000000,0.000000,NaN,0,0.000000,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9306,2024-04,National,ST MALO,PARIS MONTPARNASSE,153,95,0,1,1.533333,-0.179298,7,26.600000,3.495789,NaN,4,37.483333,3,0,14.285714,0.000000,14.285714,57.142857,0.000000,14.285714
9360,2024-05,International,PARIS LYON,BARCELONA,409,64,0,6,1.494444,-0.166667,0,0.000000,0.000000,NaN,0,0.000000,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9569,2024-06,National,ST MALO,PARIS MONTPARNASSE,153,95,0,3,3.061111,-0.085263,10,29.771667,4.171053,NaN,5,45.613333,3,1,0.000000,30.000000,30.000000,20.000000,0.000000,20.000000

### Deal with "Avg delay of all trains on departure" column

The column "Avg delay of trains delayed on departure" doesn't have negative values, so we can use it to calculate the value of the column "Average delay of all trains on departure", using these formulas:

* Avg delay of trains delayed on departure = Sum of delays at departure / Number of trains delayed on departure

* Avg delay of all trains on departure = Sum of delays on departure / Number of trips scheduled

* ##### => Avg delay of all trains on departure = Avg delay of trains delayed on departure * Number of trains delayed on departure / Number of trips scheduled

With the exception where the Number of trips scheduled is 0 ; then the avg delay has to be 0.

In [10]:
# Calculate the replacement values
replacement_values = np.where(
    df_delay_tgv["Number of trips scheduled"] != 0,
    df_delay_tgv["Avg delay of trains delayed on departure"] *
    df_delay_tgv["Number of trains delayed on departure"] /
    df_delay_tgv["Number of trips scheduled"],
    0
)

In [11]:
# Replace the negative values in "Average delay of all trains at departure"
df_delay_tgv.loc[df_delay_tgv["Avg delay of all trains on departure"] < 0, "Avg delay of all trains on departure"] = replacement_values[df_delay_tgv["Avg delay of all trains on departure"] < 0]

In [12]:
# Check result
df_delay_tgv.loc[df_delay_tgv['Avg delay of all trains on departure'] < 0]

Empty DataFrame
Columns: [Date, Service, Departure station, Arrival station, Avg trip length, Number of trips scheduled, Number of trains cancelled, Number of trains delayed on departure, Avg delay of trains delayed on departure, Avg delay of all trains on departure, Number of trains delayed on arrival, Avg delay of trains delayed on arrival, Avg delay of all trains on arrival, Comments delay on arrival, Number of trains >15 min delay, Avg delay of trains >15 (if trip has a flight concurrence), Number of trains >30 min delay, Number of trains >60 min delay, % delay from external causes, % delay infrastructure cause, % delay traffic management cause, % delay rolling stock cause, % delay station management and reutilization of stock, % delay because of accommodation of passengers (crowd, disability, connections)]
Index: []

In [13]:
# Check result
df_delay_tgv.describe()

,Avg trip length,Number of trips scheduled,Number of trains cancelled,Number of trains delayed on departure,Avg delay of trains delayed on departure,Avg delay of all trains on departure,Number of trains delayed on arrival,Avg delay of trains delayed on arrival,Avg delay of all trains on arrival,Number of trains >15 min delay,Avg delay of trains >15 (if trip has a flight concurrence),Number of trains >30 min delay,Number of trains >60 min delay,% delay from external causes,% delay infrastructure cause,% delay traffic management cause,% delay rolling stock cause,% delay station management and reutilization of stock,"% delay because of accommodation of passengers (crowd, disability, connections)"
count,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000
mean,170.010940,265.281413,10.070744,87.775891,11.597082,3.136249,36.074495,34.170000,5.785380,25.588248,33.754032,12.169098,4.459158,22.074921,21.992758,19.730230,19.048353,7.072200,7.445573
std,87.300663,178.879185,24.784164,89.711554,11.918225,4.101583,30.557789,15.491757,7.469440,21.927697,19.720504,11.440176,5.079933,16.423143,15.346118,14.965066,13.903218,8.094415,9.960441
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-40.109259,-472.638889,0.000000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,100.000000,147.000000,0.000000,22.000000,5.588875,1.174019,14.000000,24.967716,3.245905,10.000000,22.725868,4.000000,1.000000,10.714286,11.764706,9.523810,10.000000,0.000000,0.000000
50%,163.000000,227.000000,2.000000,54.000000,9.565817,2.263914,28.000000,32.599802,5.103441,20.000000,35.971216,9.000000,3.000000,20.000000,20.000000,17.857143,17.274536,5.555556,4.477612
75%,222.000000,346.000000,8.000000,128.000000,14.724359,3.904016,49.000000,41.365968,7.783922,35.000000,44.931399,17.000000,6.000000,30.769231,30.000000,27.586207,26.000000,10.569227,11.111111
max,786.000000,1100.000000,297.000000,596.000000,316.188095,84.516667,376.000000,299.600000,92.000000,312.000000,299.600000,202.000000,71.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

All good, the column doesn't have negative values anymore.

### Deal with "Avg delay of trains delayed on arrival" column

In [14]:
df_delay_tgv.loc[df_delay_tgv['Avg delay of trains delayed on arrival'] < 0]

,Date,Service,Departure station,Arrival station,Avg trip length,Number of trips scheduled,Number of trains cancelled,Number of trains delayed on departure,Avg delay of trains delayed on departure,Avg delay of all trains on departure,Number of trains delayed on arrival,Avg delay of trains delayed on arrival,Avg delay of all trains on arrival,Comments delay on arrival,Number of trains >15 min delay,Avg delay of trains >15 (if trip has a flight concurrence),Number of trains >30 min delay,Number of trains >60 min delay,% delay from external causes,% delay infrastructure cause,% delay traffic management cause,% delay rolling stock cause,% delay station management and reutilization of stock,"% delay because of accommodation of passengers (crowd, disability, connections)"
2886,2019-11,National,MONTPELLIER,PARIS LYON,380,227,11,189,4.910406,4.277469,44,-30.512500,-150.562114,NaN,44,34.677381,18,3,52.272727,13.636364,15.909091,15.909091,2.272727,0.00000
2889,2019-11,National,NIMES,PARIS LYON,224,226,11,190,8.765614,7.369322,63,-40.109259,-151.291008,NaN,44,34.677381,18,3,46.774194,17.741935,14.516129,12.903226,3.225806,4.83871

There are only 2 negative values - these are two lines with Paris Lyon as arrival station, in Nov 2019. The absolute values of those negative numbers are close enough to the mean of the column (34.17), which suggests that the error might only be the minus sign in front of the number. Let's replace them with their absolute values.

In [15]:
df_delay_tgv.loc[df_delay_tgv["Avg delay of trains delayed on arrival"] < 0, "Avg delay of trains delayed on arrival"] = df_delay_tgv['Avg delay of trains delayed on arrival'].abs()

In [16]:
# Check result
df_delay_tgv.loc[df_delay_tgv['Avg delay of trains delayed on arrival'] < 0]

Empty DataFrame
Columns: [Date, Service, Departure station, Arrival station, Avg trip length, Number of trips scheduled, Number of trains cancelled, Number of trains delayed on departure, Avg delay of trains delayed on departure, Avg delay of all trains on departure, Number of trains delayed on arrival, Avg delay of trains delayed on arrival, Avg delay of all trains on arrival, Comments delay on arrival, Number of trains >15 min delay, Avg delay of trains >15 (if trip has a flight concurrence), Number of trains >30 min delay, Number of trains >60 min delay, % delay from external causes, % delay infrastructure cause, % delay traffic management cause, % delay rolling stock cause, % delay station management and reutilization of stock, % delay because of accommodation of passengers (crowd, disability, connections)]
Index: []

All good, the column doesn't have negative values anymore.

### Deal with "Avg delay of all trains on arrival" column

In [17]:
# Observe the negative values
df_delay_tgv.loc[df_delay_tgv['Avg delay of all trains on arrival'] < 0]

,Date,Service,Departure station,Arrival station,Avg trip length,Number of trips scheduled,Number of trains cancelled,Number of trains delayed on departure,Avg delay of trains delayed on departure,Avg delay of all trains on departure,Number of trains delayed on arrival,Avg delay of trains delayed on arrival,Avg delay of all trains on arrival,Comments delay on arrival,Number of trains >15 min delay,Avg delay of trains >15 (if trip has a flight concurrence),Number of trains >30 min delay,Number of trains >60 min delay,% delay from external causes,% delay infrastructure cause,% delay traffic management cause,% delay rolling stock cause,% delay station management and reutilization of stock,"% delay because of accommodation of passengers (crowd, disability, connections)"
419,2018-04,International,MARSEILLE ST CHARLES,MADRID,464,23,16,2,1.208333,0.383333,0,0.000000,-2.714286,NaN,0,-2.714286,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
505,2018-04,National,PARIS VAUGIRARD,BORDEAUX ST JEAN,165,57,15,4,6.733333,0.099603,2,17.300000,-0.160714,NaN,1,-0.160714,0,0,0.000000,0.000000,0.000000,100.000000,0.000000,0.0
1074,2018-09,National,PARIS MONTPARNASSE,ST MALO,171,97,0,4,4.279167,0.176460,2,18.875000,-2.404296,NaN,1,-2.404296,0,0,0.000000,50.000000,50.000000,0.000000,0.000000,0.0
1099,2018-09,National,RENNES,PARIS VAUGIRARD,116,27,0,2,2.275000,0.174074,0,0.000000,-0.326543,NaN,0,-0.326543,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1739,2019-02,International,MARSEILLE ST CHARLES,MADRID,464,28,0,10,2.031667,0.916667,1,37.000000,-1.571429,NaN,1,-1.571429,1,0,0.000000,0.000000,100.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8255,2023-07,National,TOURCOING,BORDEAUX ST JEAN,304,29,0,4,2.750000,0.393103,1,35.783333,-2.761494,NaN,1,35.783333,1,0,100.000000,0.000000,0.000000,0.000000,0.000000,0.0
8318,2023-08,National,TOURCOING,BORDEAUX ST JEAN,304,28,0,1,3.000000,0.107143,1,31.750000,-0.491667,NaN,1,31.750000,1,0,0.000000,0.000000,0.000000,100.000000,0.000000,0.0
8973,2024-01,International,PARIS EST,FRANCFORT,258,120,58,5,3.743333,0.302778,8,26.937500,-0.014722,NaN,8,26.937500,3,0,0.000000,42.857143,42.857143,14.285714,0.000000,0.0
9013,2024-02,National,PARIS MONTPARNASSE,TOULOUSE MATABIAU,271,207,11,23,10.257246,0.753061,15,50.136667,-0.566667,NaN,15,50.136667,7,4,26.666667,33.333333,0.000000,13.333333,6.666667,20.0
9426,2024-05,National,STRASBOURG,NANTES,335,57,0,7,4.700000,0.640351,0,0.000000,-0.286257,NaN,0,0.000000,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0

Let's proceed in a similar fashion as the for column "Avg delay of all trains on departure". Based on the same logic:

Avg delay of all trains on arrival = Avg delay of trains delayed on arrival * Number of trains delayed on arrival / Number of trips scheduled

Unless the Number of trips scheduled = 0; then, the value is 0.

In [18]:
# Calculate the replacement values
replacement_values2 = np.where(
    df_delay_tgv["Number of trips scheduled"] != 0,
    df_delay_tgv["Avg delay of trains delayed on arrival"] *
    df_delay_tgv["Number of trains delayed on arrival"] /
    df_delay_tgv["Number of trips scheduled"],
    0
)

In [19]:
# Replace the negative values in "Average delay of all trains at departure"
df_delay_tgv.loc[df_delay_tgv["Avg delay of all trains on arrival"] < 0, "Avg delay of all trains on arrival"] = replacement_values2[df_delay_tgv["Avg delay of all trains on arrival"] < 0]

In [20]:
# Check result
df_delay_tgv.describe()

,Avg trip length,Number of trips scheduled,Number of trains cancelled,Number of trains delayed on departure,Avg delay of trains delayed on departure,Avg delay of all trains on departure,Number of trains delayed on arrival,Avg delay of trains delayed on arrival,Avg delay of all trains on arrival,Number of trains >15 min delay,Avg delay of trains >15 (if trip has a flight concurrence),Number of trains >30 min delay,Number of trains >60 min delay,% delay from external causes,% delay infrastructure cause,% delay traffic management cause,% delay rolling stock cause,% delay station management and reutilization of stock,"% delay because of accommodation of passengers (crowd, disability, connections)"
count,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000
mean,170.010940,265.281413,10.070744,87.775891,11.597082,3.136249,36.074495,34.184716,5.961176,25.588248,33.754032,12.169098,4.459158,22.074921,21.992758,19.730230,19.048353,7.072200,7.445573
std,87.300663,178.879185,24.784164,89.711554,11.918225,4.101583,30.557789,15.459253,4.151375,21.927697,19.720504,11.440176,5.079933,16.423143,15.346118,14.965066,13.903218,8.094415,9.960441
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,100.000000,147.000000,0.000000,22.000000,5.588875,1.174019,14.000000,24.984962,3.257813,10.000000,22.725868,4.000000,1.000000,10.714286,11.764706,9.523810,10.000000,0.000000,0.000000
50%,163.000000,227.000000,2.000000,54.000000,9.565817,2.263914,28.000000,32.601505,5.110889,20.000000,35.971216,9.000000,3.000000,20.000000,20.000000,17.857143,17.274536,5.555556,4.477612
75%,222.000000,346.000000,8.000000,128.000000,14.724359,3.904016,49.000000,41.365968,7.791706,35.000000,44.931399,17.000000,6.000000,30.769231,30.000000,27.586207,26.000000,10.569227,11.111111
max,786.000000,1100.000000,297.000000,596.000000,316.188095,84.516667,376.000000,299.600000,92.000000,312.000000,299.600000,202.000000,71.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

All good, the column doesn't have negative values anymore.

#### Deal with "Avg delay of trains >15 (if trip has a flight concurrence)" column

This column is actually not supposed to have any value under 15.

In [21]:
# Locate values under 15
df_delay_tgv.loc[df_delay_tgv['Avg delay of trains >15 (if trip has a flight concurrence)'] < 15]

,Date,Service,Departure station,Arrival station,Avg trip length,Number of trips scheduled,Number of trains cancelled,Number of trains delayed on departure,Avg delay of trains delayed on departure,Avg delay of all trains on departure,Number of trains delayed on arrival,Avg delay of trains delayed on arrival,Avg delay of all trains on arrival,Comments delay on arrival,Number of trains >15 min delay,Avg delay of trains >15 (if trip has a flight concurrence),Number of trains >30 min delay,Number of trains >60 min delay,% delay from external causes,% delay infrastructure cause,% delay traffic management cause,% delay rolling stock cause,% delay station management and reutilization of stock,"% delay because of accommodation of passengers (crowd, disability, connections)"
0,2018-01,National,BORDEAUX ST JEAN,PARIS MONTPARNASSE,141,870,5,289,11.247809,3.693179,147,28.436735,6.511118,NaN,110,6.511118,44,8,36.134454,31.092437,10.924370,15.966387,5.042017,0.840336
1,2018-01,National,LA ROCHELLE VILLE,PARIS MONTPARNASSE,165,222,0,8,2.875000,0.095796,34,21.524020,5.696096,NaN,22,5.696096,5,0,15.384615,30.769231,38.461538,11.538462,3.846154,0.000000
2,2018-01,National,PARIS MONTPARNASSE,QUIMPER,220,248,1,37,9.501351,1.003981,26,55.692308,7.578947,"Ce mois-ci, l'OD a été touchée par les inciden...",26,7.548387,17,7,26.923077,38.461538,15.384615,19.230769,0.000000,0.000000
3,2018-01,National,PARIS MONTPARNASSE,ST MALO,156,102,0,12,19.912500,1.966667,13,48.623077,6.790686,"Ce mois-ci, l'OD a été touchée par les inciden...",8,6.724757,6,4,23.076923,46.153846,7.692308,15.384615,7.692308,0.000000
4,2018-01,National,PARIS MONTPARNASSE,ST PIERRE DES CORPS,61,391,2,61,7.796995,0.886889,71,12.405164,3.346487,NaN,17,3.346487,6,0,21.212121,42.424242,9.090909,21.212121,6.060606,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9333,2024-04,International,PARIS LYON,ITALIE,502,28,0,1,14.766667,0.459524,0,0.000000,0.000000,NaN,0,0.000000,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9360,2024-05,International,PARIS LYON,BARCELONA,409,64,0,6,1.494444,0.140104,0,0.000000,0.000000,NaN,0,0.000000,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9426,2024-05,National,STRASBOURG,NANTES,335,57,0,7,4.700000,0.640351,0,0.000000,0.000000,NaN,0,0.000000,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9432,2024-05,International,PARIS LYON,ITALIE,502,18,0,2,10.741667,1.194444,0,0.000000,0.000000,NaN,0,0.000000,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9546,2024-06,International,PARIS LYON,BARCELONA,409,70,0,8,10.039583,0.878095,0,0.000000,0.000000,NaN,0,0.000000,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

2157 rows with an incoherent value out of the 9598 rows of the data set: that's 22%. This is way too much to impute values or delete the rows without affecting the analysis. This variable is not very interesting, it is out of the scope of our topic: let's simply delete the column.

In [22]:
df_delay_tgv = df_delay_tgv.drop(columns = ['Avg delay of trains >15 (if trip has a flight concurrence)'])

In [23]:
# Check result
df_delay_tgv.describe()

,Avg trip length,Number of trips scheduled,Number of trains cancelled,Number of trains delayed on departure,Avg delay of trains delayed on departure,Avg delay of all trains on departure,Number of trains delayed on arrival,Avg delay of trains delayed on arrival,Avg delay of all trains on arrival,Number of trains >15 min delay,Number of trains >30 min delay,Number of trains >60 min delay,% delay from external causes,% delay infrastructure cause,% delay traffic management cause,% delay rolling stock cause,% delay station management and reutilization of stock,"% delay because of accommodation of passengers (crowd, disability, connections)"
count,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000,9598.000000
mean,170.010940,265.281413,10.070744,87.775891,11.597082,3.136249,36.074495,34.184716,5.961176,25.588248,12.169098,4.459158,22.074921,21.992758,19.730230,19.048353,7.072200,7.445573
std,87.300663,178.879185,24.784164,89.711554,11.918225,4.101583,30.557789,15.459253,4.151375,21.927697,11.440176,5.079933,16.423143,15.346118,14.965066,13.903218,8.094415,9.960441
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,100.000000,147.000000,0.000000,22.000000,5.588875,1.174019,14.000000,24.984962,3.257813,10.000000,4.000000,1.000000,10.714286,11.764706,9.523810,10.000000,0.000000,0.000000
50%,163.000000,227.000000,2.000000,54.000000,9.565817,2.263914,28.000000,32.601505,5.110889,20.000000,9.000000,3.000000,20.000000,20.000000,17.857143,17.274536,5.555556,4.477612
75%,222.000000,346.000000,8.000000,128.000000,14.724359,3.904016,49.000000,41.365968,7.791706,35.000000,17.000000,6.000000,30.769231,30.000000,27.586207,26.000000,10.569227,11.111111
max,786.000000,1100.000000,297.000000,596.000000,316.188095,84.516667,376.000000,299.600000,92.000000,312.000000,202.000000,71.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

The column was successfully dropped.

### Deal with "Avg trip length" column

The column "Avg trip length" should never take the value 0, but it is its minimum value. Let's have a look:

In [24]:
pd.set_option('display.max_rows', None)
df_delay_tgv.loc[df_delay_tgv['Avg trip length'] == 0]

,Date,Service,Departure station,Arrival station,Avg trip length,Number of trips scheduled,Number of trains cancelled,Number of trains delayed on departure,Avg delay of trains delayed on departure,Avg delay of all trains on departure,Number of trains delayed on arrival,Avg delay of trains delayed on arrival,Avg delay of all trains on arrival,Comments delay on arrival,Number of trains >15 min delay,Number of trains >30 min delay,Number of trains >60 min delay,% delay from external causes,% delay infrastructure cause,% delay traffic management cause,% delay rolling stock cause,% delay station management and reutilization of stock,"% delay because of accommodation of passengers (crowd, disability, connections)"
3406,2020-04,National,PARIS MONTPARNASSE,ST MALO,0,0,8,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3413,2020-04,National,MARNE LA VALLEE,LYON PART DIEU,0,0,21,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3414,2020-04,National,MARNE LA VALLEE,MARSEILLE ST CHARLES,0,0,14,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3415,2020-04,National,MARSEILLE ST CHARLES,MARNE LA VALLEE,0,0,13,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3416,2020-04,National,PARIS LYON,ANNECY,0,0,7,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3417,2020-04,National,ANNECY,PARIS LYON,0,0,7,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3418,2020-04,National,PARIS LYON,BELLEGARDE (AIN),0,0,15,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3423,2020-04,National,PARIS LYON,PERPIGNAN,0,0,11,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3424,2020-04,National,TOULON,PARIS LYON,0,0,14,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3427,2020-04,International,FRANCFORT,PARIS EST,0,0,12,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3429,2020-04,International,BARCELONA,PARIS LYON,0,0,2,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3432,2020-04,National,LA ROCHELLE VILLE,PARIS MONTPARNASSE,0,0,13,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3436,2020-04,National,PARIS MONTPARNASSE,TOURS,0,0,9,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3437,2020-04,National,TOURS,PARIS MONTPARNASSE,0,0,11,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3438,2020-04,National,LYON PART DIEU,RENNES,0,0,4,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3440,2020-04,National,PARIS NORD,DUNKERQUE,0,0,14,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3441,2020-04,National,DUNKERQUE,PARIS NORD,0,0,15,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3442,2020-04,National,MARSEILLE ST CHARLES,LILLE,0,0,11,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3443,2020-04,National,MARSEILLE ST CHARLES,TOURCOING,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3445,2020-04,National,BELLEGARDE (AIN),PARIS LYON,0,0,14,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3447,2020-04,National,PARIS LYON,GRENOBLE,0,0,10,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3451,2020-04,National,PARIS LYON,SAINT ETIENNE CHATEAUCREUX,0,0,4,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3457,2020-04,National,PARIS MONTPARNASSE,LA ROCHELLE VILLE,0,0,15,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3466,2020-04,National,STRASBOURG,NANTES,0,0,2,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3467,2020-04,National,PARIS NORD,DOUAI,0,0,12,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3469,2020-04,National,LILLE,MARSEILLE ST CHARLES,0,0,13,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3473,2020-04,International,PARIS EST,FRANCFORT,0,0,12,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3474,2020-04,International,PARIS LYON,GENEVE,0,0,9,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3475,2020-04,International,GENEVE,PARIS LYON,0,0,10,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3476,2020-04,International,PARIS LYON,LAUSANNE,0,0,7,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3479,2020-04,National,ST MALO,PARIS MONTPARNASSE,0,0,4,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3487,2020-04,National,LYON PART DIEU,MARNE LA VALLEE,0,0,19,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3488,2020-04,National,PARIS LYON,AIX EN PROVENCE TGV,0,0,17,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3492,2020-04,National,PARIS LYON,CHAMBERY CHALLES LES EAUX,0,0,15,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3493,2020-04,National,CHAMBERY CHALLES LES EAUX,PARIS LYON,0,0,13,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3500,2020-04,International,PARIS LYON,ITALIE,0,0,4,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3506,2020-04,National,RENNES,LYON PART DIEU,0,0,4,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3509,2020-04,National,NANTES,STRASBOURG,0,0,2,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3511,2020-04,National,BORDEAUX ST JEAN,TOURCOING,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3512,2020-04,National,TOURCOING,BORDEAUX ST JEAN,0,0,2,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3514,2020-04,National,GRENOBLE,PARIS LYON,0,0,9,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3516,2020-04,National,PARIS LYON,NICE VILLE,0,0,9,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3517,2020-04,National,NICE VILLE,PARIS LYON,0,0,12,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3519,2020-04,National,PERPIGNAN,PARIS LYON,0,0,10,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3520,2020-04,National,SAINT ETIENNE CHATEAUCREUX,PARIS LYON,0,0,4,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3521,2020-04,National,PARIS LYON,TOULON,0,0,13,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3523,2020-04,International,ITALIE,PARIS LYON,0,0,3,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3524,2020-04,International,LAUSANNE,PARIS LYON,0,0,9,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3526,2020-04,International,MADRID,MARSEILLE ST CHARLES,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3527,2020-04,International,MARSEILLE ST CHARLES,MADRID,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3552,2020-05,International,MADRID,MARSEILLE ST CHARLES,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3567,2020-05,National,MARSEILLE ST CHARLES,TOURCOING,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3604,2020-05,National,STRASBOURG,NANTES,0,0,2,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3605,2020-05,National,NANTES,STRASBOURG,0,0,2,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3621,2020-05,National,PARIS LYON,SAINT ETIENNE CHATEAUCREUX,0,0,4,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3624,2020-05,International,MARSEILLE ST CHARLES,MADRID,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3635,2020-05,National,BORDEAUX ST JEAN,TOURCOING,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3636,2020-05,National,TOURCOING,BORDEAUX ST JEAN,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3642,2020-05,National,SAINT ETIENNE CHATEAUCREUX,PARIS LYON,0,0,4,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3664,2020-06,International,PARIS EST,STUTTGART,0,0,2,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3690,2020-06,International,STUTTGART,PARIS EST,0,0,2,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3692,2020-06,International,MADRID,MARSEILLE ST CHARLES,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3740,2020-06,International,MARSEILLE ST CHARLES,MADRID,0,0,1,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3966,2020-08,International,MARSEILLE ST CHARLES,MADRID,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3991,2020-08,International,MADRID,MARSEILLE ST CHARLES,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4042,2020-09,International,MADRID,MARSEILLE ST CHARLES,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4067,2020-09,International,MARSEILLE ST CHARLES,MADRID,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4192,2020-10,International,MADRID,MARSEILLE ST CHARLES,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4235,2020-10,International,MARSEILLE ST CHARLES,MADRID,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4320,2020-11,International,MADRID,MARSEILLE ST CHARLES,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4321,2020-11,International,MARSEILLE ST CHARLES,MADRID,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4432,2020-12,International,MADRID,MARSEILLE ST CHARLES,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4510,2020-12,International,MARSEILLE ST CHARLES,MADRID,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

All of those rows are from 2020, mostly April and May: it's probably due to Covid-19 pandemic disturbance. For all the rows, the value of "Number of trips scheduled" is 0, but "Number of trains cancelled" is mostly not 0. Let's look at the "0" in "Number of trips scheduled".

In [25]:
pd.set_option('display.max_rows', 10)
df_delay_tgv.loc[df_delay_tgv['Number of trips scheduled'] == 0]

,Date,Service,Departure station,Arrival station,Avg trip length,Number of trips scheduled,Number of trains cancelled,Number of trains delayed on departure,Avg delay of trains delayed on departure,Avg delay of all trains on departure,Number of trains delayed on arrival,Avg delay of trains delayed on arrival,Avg delay of all trains on arrival,Comments delay on arrival,Number of trains >15 min delay,Number of trains >30 min delay,Number of trains >60 min delay,% delay from external causes,% delay infrastructure cause,% delay traffic management cause,% delay rolling stock cause,% delay station management and reutilization of stock,"% delay because of accommodation of passengers (crowd, disability, connections)"
3406,2020-04,National,PARIS MONTPARNASSE,ST MALO,0,0,8,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3413,2020-04,National,MARNE LA VALLEE,LYON PART DIEU,0,0,21,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3414,2020-04,National,MARNE LA VALLEE,MARSEILLE ST CHARLES,0,0,14,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3415,2020-04,National,MARSEILLE ST CHARLES,MARNE LA VALLEE,0,0,13,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3416,2020-04,National,PARIS LYON,ANNECY,0,0,7,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,2020-10,International,MARSEILLE ST CHARLES,MADRID,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4320,2020-11,International,MADRID,MARSEILLE ST CHARLES,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4321,2020-11,International,MARSEILLE ST CHARLES,MADRID,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4432,2020-12,International,MADRID,MARSEILLE ST CHARLES,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4510,2020-12,International,MARSEILLE ST CHARLES,MADRID,0,0,0,0,0.0,0.0,0,0.0,0.0,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

These are the very same rows. The issue, then, is that the "Number of train cancelled" is not always 0 and is higher than the number of trips scheduled, which doesn't make sense. Let's change the value of "Number of trains cancelled" to 0.

In [26]:
df_delay_tgv.loc[df_delay_tgv['Number of trips scheduled'] == 0, 'Number of trains cancelled'] = 0

## 3.4 Missing values

In [27]:
pd.set_option('display.max_rows', None)
df_delay_tgv.isnull().sum()

Date                                                                                  0
Service                                                                               0
Departure station                                                                     0
Arrival station                                                                       0
Avg trip length                                                                       0
Number of trips scheduled                                                             0
Number of trains cancelled                                                            0
Number of trains delayed on departure                                                 0
Avg delay of trains delayed on departure                                              0
Avg delay of all trains on departure                                                  0
Number of trains delayed on arrival                                                   0
Avg delay of trains delayed on arrival                                                0
Avg delay of all trains on arrival                                                    0
Comments delay on arrival                                                          8900
Number of trains >15 min delay                                                        0
Number of trains >30 min delay                                                        0
Number of trains >60 min delay                                                        0
% delay from external causes                                                          0
% delay infrastructure cause                                                          0
% delay traffic management cause                                                      0
% delay rolling stock cause                                                           0
% delay station management and reutilization of stock                                 0
% delay because of accommodation of passengers (crowd, disability, connections)       0
dtype: int64

The only column with missing values is "Comments delay at arrival", which is fine: it's a column of unstructured data anyway. I prefer not to get rid of the column because it might give us some insights later, if I get some surprising results or outliers in my analysis.

## 3.5 Duplicates

In [28]:
#view duplicates
df_delay_tgv[df_delay_tgv.duplicated()]

Empty DataFrame
Columns: [Date, Service, Departure station, Arrival station, Avg trip length, Number of trips scheduled, Number of trains cancelled, Number of trains delayed on departure, Avg delay of trains delayed on departure, Avg delay of all trains on departure, Number of trains delayed on arrival, Avg delay of trains delayed on arrival, Avg delay of all trains on arrival, Comments delay on arrival, Number of trains >15 min delay, Number of trains >30 min delay, Number of trains >60 min delay, % delay from external causes, % delay infrastructure cause, % delay traffic management cause, % delay rolling stock cause, % delay station management and reutilization of stock, % delay because of accommodation of passengers (crowd, disability, connections)]
Index: []

No duplicates.

## 3.6 Mixed-types columns

In [29]:
for col in df_delay_tgv.columns.tolist():
  weird = (df_delay_tgv[[col]].applymap(type) != df_delay_tgv[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_delay_tgv[weird]) > 0:
    print (col)

Comments delay on arrival

The column "Comments delay at arrival" is mixed-type: let's change it all to string.

In [30]:
df_delay_tgv['Comments delay on arrival'] = df_delay_tgv['Comments delay on arrival'].astype('str')

## 3.7 Export cleaned TGV data set

In [31]:
df_delay_tgv.to_csv(os.path.join(path, '02 Data','Prepared Data', 'delay_tgv_clean.csv'))

# 4. Explore and clean Number of travelers data set

In [32]:
df_nb_travelers.head()

,Nom de la gare,Code UIC,Code postal,Segmentation DRG,Total Voyageurs 2023,Total Voyageurs + Non voyageurs 2023,Total Voyageurs 2022,Total Voyageurs + Non voyageurs 2022,Total Voyageurs 2021,Total Voyageurs + Non voyageurs 2021,Total Voyageurs 2020,Total Voyageurs + Non voyageurs 2020,Total Voyageurs 2019,Total Voyageurs + Non voyageurs 2019,Total Voyageurs 2018,Total Voyageurs + Non voyageurs 2018,Total Voyageurs 2017,Total Voyageurs + Non voyageurs 2017,Total Voyageurs 2016,Total Voyageurs + Non voyageurs 2016,Total Voyageurs 2015,Total Voyageurs + Non voyageurs 2015
0,Abancourt,87313759,60220,C,77974,77974,71517,71517,51811,51811,32396,32396,42685,42685,40228,40228,43760,43760,41096,41096,39720,39720
1,Agde,87781278,34300,B,757491,946864,689202,861503,561160,701450,394380,492975,542288,677860,588297,735372,697091,871364,660656,825820,662516,828146
2,Agen,87586008,47000,A,1640325,2050407,1540511,1925639,1184007,1480009,860964,1076205,1211323,1514154,1109199,1386499,1194455,1493068,1141620,1427026,1183150,1478938
3,Agonac,87595157,24460,C,9537,9537,6468,6468,4119,4119,3271,3271,2538,2538,1492,1492,1583,1583,1134,1134,1127,1127
4,Aguilcourt - Variscourt,87171702,2190,C,13464,13464,13197,13197,12294,12294,10436,10436,8796,8796,6155,6155,7368,7368,8979,8979,9821,9821

## 4.1 Drop useless columns

For each year, we have a column for the number of travelers and the number of travelers + visitors who didn't travel. We don't need the latest. We don't need the postal code either, nor the Segmentation DRG. Let's trop all of that. I'll keep "Code IUC", which is an unique identifier for train stations, because some train stations might have the same name and we'll need to distinguish them.

In [33]:
df_nb_travelers = df_nb_travelers.drop(columns=['Code postal', 'Segmentation DRG', 'Total Voyageurs + Non voyageurs 2023', 'Total Voyageurs + Non voyageurs 2022', 'Total Voyageurs + Non voyageurs 2021', 'Total Voyageurs + Non voyageurs 2020', 'Total Voyageurs + Non voyageurs 2019', 'Total Voyageurs + Non voyageurs 2018', 'Total Voyageurs + Non voyageurs 2017', 'Total Voyageurs + Non voyageurs 2016', 'Total Voyageurs + Non voyageurs 2015'])

In [34]:
df_nb_travelers.head(1)

,Nom de la gare,Code UIC,Total Voyageurs 2023,Total Voyageurs 2022,Total Voyageurs 2021,Total Voyageurs 2020,Total Voyageurs 2019,Total Voyageurs 2018,Total Voyageurs 2017,Total Voyageurs 2016,Total Voyageurs 2015
0,Abancourt,87313759,77974,71517,51811,32396,42685,40228,43760,41096,39720

## 4.2 Rename columns to English

In [35]:
df_nb_travelers.rename(columns={
    "Nom de la gare": "Station name",
    "Code UIC": "UIC code",
    "Total Voyageurs 2023": "Total travelers 2023",
    "Total Voyageurs 2022": "Total travelers 2022",
    "Total Voyageurs 2021": "Total travelers 2021",
    "Total Voyageurs 2020": "Total travelers 2020",
    "Total Voyageurs 2019": "Total travelers 2019",
    "Total Voyageurs 2018": "Total travelers 2018",
    "Total Voyageurs 2017": "Total travelers 2017",
    "Total Voyageurs 2016": "Total travelers 2016",
    "Total Voyageurs 2015": "Total travelers 2015",
}, inplace = True)

## 4.3 Deal with outliers/impossible values

In [36]:
df_nb_travelers.describe()

,UIC code,Total travelers 2023,Total travelers 2022,Total travelers 2021,Total travelers 2020,Total travelers 2019,Total travelers 2018,Total travelers 2017,Total travelers 2016,Total travelers 2015
count,3.010000e+03,3.010000e+03,3.010000e+03,3.010000e+03,3.010000e+03,3.010000e+03,3.010000e+03,3.010000e+03,3.010000e+03,3.010000e+03
mean,8.748935e+07,9.281000e+05,8.656592e+05,6.908668e+05,4.760994e+05,9.104975e+05,8.934209e+05,9.097895e+05,8.826474e+05,8.728819e+05
std,2.067503e+05,5.795150e+06,5.438984e+06,3.982991e+06,3.227785e+06,6.096153e+06,6.078375e+06,6.158213e+06,6.018658e+06,5.938435e+06
min,8.700970e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.731325e+07,1.127850e+04,1.024800e+04,7.463000e+03,5.528250e+03,7.721000e+03,6.801750e+03,7.503750e+03,7.645000e+03,7.789750e+03
50%,8.748726e+07,5.862850e+04,5.220250e+04,3.857650e+04,3.061650e+04,4.436550e+04,4.024950e+04,4.338750e+04,4.170700e+04,4.334500e+04
75%,8.768411e+07,2.921128e+05,2.630058e+05,2.054730e+05,1.562675e+05,2.384548e+05,2.199030e+05,2.334558e+05,2.235845e+05,2.303582e+05
max,8.798872e+07,2.267685e+08,2.116985e+08,1.266210e+08,1.144684e+08,2.447444e+08,2.444656e+08,2.479632e+08,2.422731e+08,2.383561e+08

The numerical values seem to make sense, except for the 0 in the min. It means a station with no travelers at all. Let's check it out.

In [37]:
pd.set_option('display.max_rows', None)
df_nb_travelers.loc[df_nb_travelers['Total travelers 2023']==0]

,Station name,UIC code,Total travelers 2023,Total travelers 2022,Total travelers 2021,Total travelers 2020,Total travelers 2019,Total travelers 2018,Total travelers 2017,Total travelers 2016,Total travelers 2015
185,Exideuil,87592881,0,0,0,0,0,0,79,288,834
221,Hymont - Mattaincourt,87144220,0,0,354,761,1058,928,695,1496,1537
346,Merrey,87142406,0,0,0,0,1,4,75,172,251
364,Montbré,87171256,0,0,0,1355,2655,2609,3307,3668,3103
388,Nonant-le-Pin,87444570,0,1,0,0,0,2,0,36,28
400,Pargny-sur-Saulx,87174334,0,0,0,0,0,0,0,0,0
418,Pont-Hébert,87447185,0,0,0,0,1,286,455,340,326
420,Pont-du-Casse,87586404,0,0,156,360,711,573,451,292,237
480,Saint-Martin-Bellevue,87746222,0,0,0,0,0,2,312,857,447
491,Saint-Sever,87447714,0,0,2,7,48,76,75,78,341
513,Acheux - Franleu,87316745,0,2,0,0,2,235,104,308,898
540,Séon Saint-Henri,87751636,0,0,0,0,63,1475,1227,645,1104
608,Vignols - Saint-Solve,87594655,0,111,211,38,51,96,374,275,365
627,Bolbec - Nointot,87413351,0,2,0,0,3280,6070,7403,7726,9072
638,Voellerdingen,87215640,0,0,0,0,0,0,0,0,0
652,Wittelsheim,87182683,0,0,0,0,351,39,0,0,0
677,Campagne-sur-Aude,87615229,0,1,3,0,0,1,27,48,26
694,Champlan,87725457,0,0,0,0,0,0,0,0,0
735,Coussac-Bonneval,87592840,0,251,137,194,323,378,868,1269,1187
788,Glos - Montfort,87415349,0,0,0,0,830,1253,772,1213,1769
884,Louhossoa,87673673,0,0,195,390,498,498,498,493,484
1022,Pontgibaud,87641316,0,1,22,55,39,417,398,140,292
1033,Quesnoy-le-Montant,87317487,0,0,0,0,96,334,431,919,1658
1048,Richwiller,87182675,0,0,0,0,0,0,0,0,0
1131,Taillebourg,87491043,0,0,0,0,663,368,453,563,252
1157,Valdieu,87181081,0,0,0,0,0,0,0,0,0
1196,Zornhoff Monswiller,87212217,0,0,0,0,0,0,0,0,0
1332,Colroy - Lubine,87144386,0,0,0,23,15,18,140,587,247
1343,Couliboeuf,87444232,0,0,0,0,346,262,1002,1013,880
1364,Douzillac,87595280,0,0,0,0,0,0,515,1425,1234
1377,Feuquerolles,87316752,0,0,0,0,10,238,397,547,574
1441,La Bachellerie,87595595,0,1,0,165,935,668,706,1061,957
1459,Labarthe-Inard,87611129,0,0,0,230,149,230,926,1310,962
1538,Milhac-d'Auberoche,87595538,0,0,0,61,436,739,1010,678,209
1610,Pommevic,87618058,0,0,0,0,28,0,248,654,563
1635,Roumazières-Loubert,87583468,0,3,0,360,2372,3106,6588,7623,8146
1636,Ruelle-sur-Touvre,87583203,0,2,0,480,956,3501,5251,5148,6692
1673,Saint-Pierre-du-Vauvray,87415646,0,0,0,0,2061,2637,2160,1598,1845
1698,Sillery,87171637,0,0,0,0,859,812,406,854,1471
1713,Tillières-sur-Avre,87393587,0,0,0,0,0,0,0,43,129
1734,Verneuil-sur-Vienne,87592675,0,0,0,1,0,0,1,10,84
1750,Villers sur Thère,87316422,0,0,0,0,0,0,0,0,270
1756,Virville - Manneville,87413336,0,0,0,0,48,2082,2391,3652,5426
1782,Andilly,87142364,0,0,0,0,0,0,0,0,0
1835,Bourth,87393603,0,0,0,0,0,0,82,469,385
1851,Carantilly - Marigny,87447144,0,0,0,0,0,1403,1948,1404,1697
1991,La Miouze - Rochefort,87641290,0,1,0,3,226,530,265,175,744
1998,La Rochefoucauld,87583427,0,2,3,1,1427,3766,11004,16401,20238
2042,Les Islettes,87175711,0,0,34,28,83,103,26,40,154
2080,Malause,87611871,0,9,0,0,0,162,432,794,1263
2092,Mauzens-et-Miremont,87595728,0,0,1,199,554,421,334,418,804
2119,Mulhouse Musées,87534339,0,0,0,0,0,0,0,0,0
2130,Nissan,87781179,0,0,0,0,0,0,0,0,1114
2164,Pierreville,87141556,0,0,268,181,0,0,270,1000,1906
2225,Saint-Germain - Saint-Rémy,87393520,0,0,0,0,0,44,2,60,476
2229,Saint-Hilaire-au-Temple,87174441,0,0,0,3,414,230,345,391,857
2364,Écouflant,87484113,0,0,0,0,0,0,209,1202,1380
2405,Ballersdorf,87181073,0,0,0,0,0,0,0,0,0
2438,Bouy,87174433,0,0,0,38,778,889,1262,964,908
2447,Brunstatt,87181032,0,0,0,0,0,0,0,0,0
2489,Chèvremont,87184259,0,0,0,0,0,0,467,792,1111
2494,Clion sur Seugne,87491134,0,0,0,0,17,19,11,10,42
2543,Fontaines-d'Ozillac,87491159,0,0,0,0,89,93,82,61,80
2545,Forges d'Abel,87672840,0,0,0,0,14,15,152,18,174
2553,Fréjus - Saint-Raphael Autotrain,87757518,0,0,1,30,7,32,51,95,4175
2583,Hasenrain,87181024,0,0,0,0,0,0,566,395,378
2693,Lesseux - Frapelle,87144329,0,0,0,0,0,3,37,389,344
2695,Liart,87172544,0,331,288,203,274,24,10,7,22
2728,Massy Europe,87725465,0,0,0,0,0,0,0,0,0
2772,Mulhouse Zu Rhein Tram-Train,87472639,0,0,0,0,0,0,0,0,0
2828,Pulligny - Autrey,87141564,0,0,268,452,952,1053,1349,1190,907
2893,Saint-Louis les Aygalades,87751644,0,0,0,0,0,0,0,16,30
2952,Trois-Puits,87171264,0,0,0,1,283,60,146,12,377
2968,Vaux-sous-Aubigny,87142620,0,0,0,0,0,2,151,524,256

In [38]:
df_nb_travelers.loc[df_nb_travelers['Total travelers 2015']==0]

,Station name,UIC code,Total travelers 2023,Total travelers 2022,Total travelers 2021,Total travelers 2020,Total travelers 2019,Total travelers 2018,Total travelers 2017,Total travelers 2016,Total travelers 2015
5,Aigrefeuille le Thou,87485193,61127,51200,32989,24987,31170,18670,14513,266,0
50,Base Aérienne,87699223,2714,2079,659,95,0,0,0,0,0
168,Delle,87184440,32269,31341,19250,17348,25996,1250,0,0,0
231,L'Etang les Sablons,87726109,148199,70338,0,0,0,0,0,0,0
242,La Couronne,87583617,364,0,0,0,0,0,0,0,0
276,Le Mans Hôpital-Université,87743872,10061,0,0,0,0,0,0,0,0
387,Noisy-le-Roi,87733659,354395,168105,0,0,0,0,0,0,0
393,Nîmes Pont du Gard,87703975,1054535,745834,590063,405086,15135,0,0,0,0
400,Pargny-sur-Saulx,87174334,0,0,0,0,0,0,0,0,0
525,Allée Royale,87710913,46010,21783,0,0,0,0,0,0,0
585,Bagnols-sur-Cèze,87764571,43039,18495,0,0,0,0,0,0,0
622,Villetaneuse Université,87697318,4152466,3902317,3126857,675432,1840999,1872981,950582,0,0
638,Voellerdingen,87215640,0,0,0,0,0,0,0,0,0
644,Wambaix,87345595,418,170,0,2,4,78,116,50,0
652,Wittelsheim,87182683,0,0,0,0,351,39,0,0,0
694,Champlan,87725457,0,0,0,0,0,0,0,0,0
812,Joncherey,87700153,7101,7473,4837,4860,3429,120,0,0,0
890,Lurbe-Saint-Christau,87672741,1828,1053,1490,1443,2048,1201,1854,851,0
965,Méroux,87184408,60663,50340,30976,19146,33018,1385,0,0,0
1018,Pont-Saint-Esprit,87764555,18675,7241,0,0,0,0,0,0,0
1048,Richwiller,87182675,0,0,0,0,0,0,0,0,0
1141,Toulon Sainte-Musse,87742262,116047,1330,0,0,0,0,0,0,0
1157,Valdieu,87181081,0,0,0,0,0,0,0,0,0
1196,Zornhoff Monswiller,87212217,0,0,0,0,0,0,0,0,0
1237,Bailly,87710780,326980,154915,0,0,0,0,0,0,0
1408,Grandvillars,87184432,10991,11796,8079,7904,6894,194,0,0,0
1453,La Jarrie,87485185,28546,27766,17939,13853,18035,9346,6372,119,0
1479,Le Bouscat - Saint-Germaine,87738096,9488,0,0,0,0,0,0,0,0
1626,Remoulins,87775395,628,762,0,0,0,0,0,0,0
1782,Andilly,87142364,0,0,0,0,0,0,0,0,0
1832,Boulazac,87725473,32033,17196,4401,53,0,0,0,0,0
1892,Danjoutin,87700146,1232,1742,1007,948,1924,87,0,0,0
2050,Lisière Pereire,87733683,521227,246807,0,0,0,0,0,0,0
2089,Marsac-sur-L'isle,87595207,5094,128,0,1,0,2,0,0,0
2108,Montpellier Sud de France,87688887,1918295,1660814,1297998,1013031,908651,410346,0,0,0
2119,Mulhouse Musées,87534339,0,0,0,0,0,0,0,0,0
2260,Sainte-Marguerite,87287193,12,4,1,1,63,16,11,8,0
2405,Ballersdorf,87181073,0,0,0,0,0,0,0,0,0
2422,Bidos,87691949,6647,5185,3220,2525,7401,4020,5771,3829,0
2447,Brunstatt,87181032,0,0,0,0,0,0,0,0,0
2531,Dugny - La Courneuve T11,87697342,1298446,1220226,977745,220312,464595,474457,240459,0,0
2598,Irigny Yvours,87722249,47037,41898,26690,24067,16431,2,0,0,0
2686,Les Portes de Saint-Cyr,87710921,53359,25258,0,0,0,0,0,0,0
2728,Massy Europe,87725465,0,0,0,0,0,0,0,0,0
2767,Morvillars,87184424,9622,9808,7125,5663,5243,138,0,0,0
2772,Mulhouse Zu Rhein Tram-Train,87472639,0,0,0,0,0,0,0,0,0
2851,Rosa Parks,87654798,12754682,11987483,5937856,2865667,9038087,9029393,9065994,8923180,0
2883,Saint-Germain-en-Laye Bel-Air - Fourqueux,87733675,800369,378967,0,0,0,0,0,0,0
2929,Stains La Cerisaie T11,87697334,2152404,2022741,1620786,370977,909932,933122,473547,0,0
2954,Trélazé,87701532,72714,60813,40738,30106,44256,1684,0,0,0

73 stations with 0 travelers in 2023: most of them still had travelers in 2015 and seem to have closed in the following years.

46 stations with no travelers in 2015: most of them start having travelers in the folowing years, they must be new stations.

Few stations with 0 travelers recorded ever. They will not disturb our analysis.

No action taken.

## 4.4 Missing values

In [39]:
df_nb_travelers.isnull().sum()

Station name            0
UIC code                0
Total travelers 2023    0
Total travelers 2022    0
Total travelers 2021    0
Total travelers 2020    0
Total travelers 2019    0
Total travelers 2018    0
Total travelers 2017    0
Total travelers 2016    0
Total travelers 2015    0
dtype: int64

No missing values.

## 4.5 Duplicates

In [40]:
# View duplicates in data set
df_nb_travelers[df_nb_travelers.duplicated()]

Empty DataFrame
Columns: [Station name, UIC code, Total travelers 2023, Total travelers 2022, Total travelers 2021, Total travelers 2020, Total travelers 2019, Total travelers 2018, Total travelers 2017, Total travelers 2016, Total travelers 2015]
Index: []

No duplicates.

In [41]:
# View duplicates in Station name column
df_nb_travelers[df_nb_travelers['Station name'].duplicated()]

,Station name,UIC code,Total travelers 2023,Total travelers 2022,Total travelers 2021,Total travelers 2020,Total travelers 2019,Total travelers 2018,Total travelers 2017,Total travelers 2016,Total travelers 2015
1813,Belleville,87141804,31805,26977,20628,17494,25006,23040,28306,28504,28800

In [42]:
df_nb_travelers.loc[df_nb_travelers['Station name'] == 'Belleville']

,Station name,UIC code,Total travelers 2023,Total travelers 2022,Total travelers 2021,Total travelers 2020,Total travelers 2019,Total travelers 2018,Total travelers 2017,Total travelers 2016,Total travelers 2015
1254,Belleville,87486142,134484,113138,71832,57289,85566,73772,67909,58233,49298
1813,Belleville,87141804,31805,26977,20628,17494,25006,23040,28306,28504,28800

Indeed, there are two stations with the same name, but as we can distinguisd them with the UIC code, it's alright.

## 4.6 Mixed-types columns

In [43]:
for col in df_nb_travelers.columns.tolist():
  weird = (df_nb_travelers[[col]].applymap(type) != df_nb_travelers[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_nb_travelers[weird]) > 0:
    print (col)

No mixed-types columns.

## 4.7 Export Number of travelers data set

In [44]:
df_nb_travelers.to_csv(os.path.join(path, '02 Data','Prepared Data', 'df_nb_travelers_clean.csv'))